### ISSUE TITLE
On-screen keyboard can cover up the comment text input field

### ISSUE THREAD

**Issue by mykdavies** [liftoff-app/liftoff#129]
### Device info

- OS: reported against iOS and Android
- Liftoff version: 0.9.18

### Describe the bug

If users are using a tall keyboard, and they have a small screen, and the comment they're replying to has taken up all its allotted area, the comment input field can be completely or partially hidden and difficult to access

### Steps to reproduce

1. Reply to any comment of more than an couple of paragraphs.

### Expected behavior

May need to slightly reduce area allowed for the comment being replied to dependent on screen size.

### Screenshots/Screencasts

Not the worst case issue of the box being totally hidden, but getting close :-)

![IMG_2690](https://github.com/liftoff-app/liftoff/assets/7827009/a82d3f7e-2ac3-4955-ae6d-c3a39f144196)

**Comment by TurnItOff-OnAgain** [comment]
I've had this happen, but I was able to scroll the page with the keyboard open. Does this not work for you?

**Comment by mykdavies** [comment]
Yes, I could in this case with a little fiddling about, but someone reported that their text field was totally covered so it was either not possible or difficult to understand how to do so.

**Comment by adrian-sal-kennedy** [comment]
> 

In my case I have a non-stock keyboard that is a little taller and so scrolling is not possible sometimes. Is there a hardcoded value in there for max keyboard height? My phone has an odd aspect ratio and is skinnier and taller than most (Samsung s9) and so I use an old people's big button keyboard because I've never had good accuracy on the stock keyboard.

My phone is good at defying UI assumptions...
