### ISSUE TITLE
Option to collapse child comments by default

### ISSUE THREAD

**Issue by varaki** [liftoff-app/liftoff#198]
### Is your feature request related to a problem? Please describe.

Make only top level comments and their contents visible, indicating the number of their child comments in the top right corner (the latter is already an existing feature) optionally in the settings.
I think it could be useful for posts where there's a lot of comments, and if someone is not interested in the toplevel comments, they probably are not in the child comments either, i.e. don't have to scroll over them.
The current manual way of collapsing results in a generic text, saying that a thread is collapsed, instead of showing the top level comment of that thread.

### Describe the solution you'd like

An option in the settings "Collapse child comments by default" which would result in all posts opened showing their top level comments only, like they were single comments, but collapsed and having the child comments number in their top right corner.

**Comment by waldyrious** [comment]
@varaki perhaps it would be clearer if this issue was titled e.g. "Option to collapse all non-top-level comments"

The "by default" part could be a setting instead; I think it would be more flexible to allow users to have the ability to toggle this on and off directly in posts as a feature in itself, and as a separate feature, be able to opt in to have the software perform this action automatically for them by indicating that in the settings.

**Comment by varaki** [comment]
> The "by default" part could be a setting instead
This is what I detailed in the "Describe the solution you'd like"

> allow users to have the ability to toggle this on and off directly in posts as a feature in itself

Yes, this can be added, too
